ci/github: Make sparse diagnostics non-fatal
Kernels as of commit ae83f3b72621 ("module: Add compile-time check for
embedded NUL characters") yield errors from sparse 0.6.4 when
expanding certain module-related macros due to the use of
__builtin_strlen() within a static_assert():

  CHECK   /src/drivers/dma/sdxi/device.c
drivers/dma/sdxi/device.c:29:1: error: bad constant expression
drivers/dma/sdxi/device.c:30:1: error: bad constant expression
drivers/dma/sdxi/device.c:33:1: error: bad constant expression
drivers/dma/sdxi/device.c:34:1: error: bad constant expression

(This happens in non-sdxi code as well.)

This diagnostic arises from non-option-controlled code in sparse and
cannot be disabled, apparently. It is not related to
-Wconstexpr-not-const; -Wno-constexpr-not-const does not prevent it.

There has been some discussion and a partial(?) fix committed to
sparse upstream, but there's no imminent solution in either Linux or
Sparse afaik:

https://lore.kernel.org/lkml/07d04170-921e-4692-8d3e-d01859d66828@kernel.org/
https://lore.kernel.org/all/aUV7kyjxlijuy5sC@agluck-desk3/
https://lore.kernel.org/lkml/aRMhLEs9NpGexL7B@black.igk.intel.com/

Continue to use sparse in the builds where it's currently used, but
downgrade the failure mode to warn-only instead of fatal throughout.

Signed-off-by: Nathan Lynch <nathan.lynch@amd.com>